[package]
name = "reatrust"
version = "0.1.9"
edition = "2024"
build = "build.rs"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[features]
default = []
verbose-logs = ["libreatrust-core/verbose-logs"]

[profile.release]
lto = "thin"
strip = "symbols"
codegen-units = 1
panic = "abort"

[dependencies]
libreatrust-core = { path = "crates/libreatrust-core" }
